site_name: 东华高中毕业生大学指北
site_url: https://musemok.github.io/university-guide/
site_author: Muse Mok

repo_name: GitHub
repo_url: https://github.com/musemok/university-guide
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections  # 添加：显示分组
    - navigation.expand    # 添加：自动展开导航
    - search.suggest
  palette: 
    primary: indigo

plugins:
  - search:
      lang:
        - en
        - ja
        - zh
      separator: '[\s\-\.\/]+'
      prebuild_index: true

nav:
  - 首页: 
    - 文档说明: index.md
    - 更新日志: 
      - 正式版更新说明: change/1.md
  - 山东:
    - 山东大学:
      - 山大计算机测如评: shandong/sdu/1.md
  - 广东:
    - 中山大学:
      - 23旅游管理灰太狼大王分享: guangdong/sysu/1.md
    - 暨南大学:
      - 乌贼分享: guangdong/jnu/1.md
  - 湖北:
    - 武汉大学:
      - 武汉大学饮食大测评: hubei/whu/1.md
      - 喜欢上热搜的大学……: hubei/whu/2.md
  - 甘肃:
    - 兰州大学:
      - 卡萨布兰卡分享: gansu/lzu/1.md
  - 其他: 
    - 其他文章: others/1.md
  