site_name: 东华高中毕业生大学指北
site_url: https://musemok.github.io/university-guide/
site_author: Muse Mok

repo_name: GitHub
repo_url: https://github.com/musemok/university-guide
edit_uri: edit/main/docs/ # 让页面显示“编辑”按钮

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - search.suggest
  palette: 
    primary: indigo

plugins:
  - search

nav:
  - 首页: index.md
  - 北京:
      - 北京大学: beijing/pku.md
  - 上海:
      - 复旦大学: shanghai/fdu.md